# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-01 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0003_auto_20170101_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='subworks',
        ),
        migrations.AddField(
            model_name='work',
            name='Subject',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subworks', to='BBproj.Subject'),
        ),
    ]
