# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-03 07:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0007_auto_20170103_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='Logintime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='userp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique_for_date='Logintime.Date'),
        ),
    ]
