# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0010_auto_20170103_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='Subject',
        ),
    ]
