# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0012_work_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Subject',
            field=models.ForeignKey(default=django.utils.timezone.now, max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='subworks', to='BBproj.Subject'),
            preserve_default=False,
        ),
    ]
