# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0014_text_append'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text_append',
            name='text',
        ),
        migrations.DeleteModel(
            name='text_append',
        ),
    ]
