# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0015_auto_20170106_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Subject_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
