# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0016_auto_20170106_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='deadline',
        ),
    ]
