# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBproj', '0017_remove_work_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
